# Clippy configuration for OTLP Rust project
# https://doc.rust-lang.org/clippy/lint_configuration.html

# Complexity thresholds
cognitive-complexity-threshold = 25
too-many-lines-threshold = 150
type-complexity-threshold = 500

# Documentation
missing-docs-in-private-items = false

# Allow certain lints that are sometimes necessary
# These should be used sparingly with good reason
avoid-breaking-exported-api = false

# Warn on these by default
warn = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::cargo",
]

# Allow these lints (with justification)
allow = [
    # Sometimes we need many arguments for builder patterns
    "clippy::too_many_arguments",
    
    # Module inception is sometimes necessary for organization
    "clippy::module_name_repetitions",
    
    # Not always practical to implement
    "clippy::must_use_candidate",
    
    # Can be overly restrictive
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc",
]

# Explicitly deny these (treat as errors)
deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::todo",
    "clippy::unimplemented",
]

