# Rustfmt configuration for OTLP Rust project
# https://rust-lang.github.io/rustfmt/

# Edition
edition = "2021"

# Line width
max_width = 100
comment_width = 100
wrap_comments = true

# Indentation
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Code style
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
match_block_trailing_comma = true
trailing_semicolon = true

# Whitespace
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
type_punctuation_density = "Wide"

# Wrapping
use_small_heuristics = "Default"
fn_single_line = false
where_single_line = false
format_strings = true
format_macro_matchers = true

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true

# Code organization
reorder_impl_items = true

# Formatting
struct_lit_single_line = true
fn_call_width = 80
attr_fn_like_width = 80
chain_width = 80

# Features
unstable_features = false

