# Rust 工具链配置文件 - 2025年最新设置
# 支持Rust 1.90新特性和性能优化

[toolchain]
# 使用最新的稳定版本
channel = "stable"
# 或者指定具体版本: channel = "1.90.0"

# 目标平台配置
targets = [
    "x86_64-pc-windows-msvc",    # Windows 64位
]

# 组件配置
components = [
    "rustfmt",      # 代码格式化
    "clippy",       # 代码检查
    "rust-src",     # 标准库源码
    "rust-analyzer", # 语言服务器
    "rust-docs",    # 文档
    "cargo",        # 包管理器
    "cargo-fmt",    # Cargo格式化
    "cargo-clippy", # Cargo代码检查
]

# 配置文件
profile = "default"

# 工具链覆盖
[toolchain.override]
# 可以在这里覆盖特定目录的工具链设置

# 环境变量
[env]
# Rust 1.90 优化环境变量
RUSTFLAGS = "-C target-cpu=native -C opt-level=3 -C lto=fat"
RUST_LOG = "info"
CARGO_INCREMENTAL = "1"
CARGO_NET_RETRY = "2"
CARGO_HTTP_TIMEOUT = "30"
CARGO_HTTP_MULTIPLEXING = "true"
CARGO_HTTP_DEBUG = "false"
CARGO_HTTP_CHECK_REVOKE = "true"
CARGO_HTTP_USE_GIT = "true"
CARGO_HTTP_LOW_SPEED_LIMIT = "1000"
CARGO_HTTP_LOW_SPEED_TIME = "30"
CARGO_HTTP_MAX_RETRIES = "3"
CARGO_HTTP_RETRY_DELAY = "1000"
CARGO_HTTP_USER_AGENT = "cargo/1.90.0"
CARGO_HTTP_PROXY = ""
CARGO_HTTP_NO_PROXY = ""
CARGO_HTTP_CAINFO = ""
CARGO_HTTP_CAPATH = ""
CARGO_HTTP_CERT = ""
CARGO_HTTP_KEY = ""
CARGO_HTTP_INSECURE = "false"
CARGO_HTTP_VERIFY_SSL = "true"

# 构建配置
[build]
# 构建目标
target = "x86_64-pc-windows-msvc"

# 构建目录
target-dir = "target"

# 并行构建
jobs = 0  # 0表示使用所有可用CPU核心

# 构建脚本
build-script = "build.rs"

# 输出目录
out-dir = "target/release"

# 增量编译
incremental = true

# 调试信息
debug = false

# 优化级别
opt-level = 3

# 链接时优化
lto = "fat"

# 代码生成单元
codegen-units = 1

# Panic策略
panic = "abort"

# 符号剥离
strip = "symbols"

# 帧指针
force-frame-pointers = false

# 重定位模型
relocation-model = "static"

# 目标CPU
target-cpu = "native"

# 目标特性
target-feature = "+crt-static,+avx2,+fma,+bmi2,+popcnt,+sse4.2"

# 链接器
linker = ""

# 链接器参数
link-args = []

# 运行时库
crt-static = true

# 标准库
std = true

# 测试配置
[test]
# 测试目标
target = "x86_64-pc-windows-msvc"

# 测试目录
target-dir = "target"

# 并行测试
jobs = 0

# 测试脚本
test-script = ""

# 输出目录
out-dir = "target/debug"

# 增量编译
incremental = true

# 调试信息
debug = true

# 优化级别
opt-level = 0

# 链接时优化
lto = false

# 代码生成单元
codegen-units = 256

# Panic策略
panic = "unwind"

# 符号剥离
strip = false

# 帧指针
force-frame-pointers = true

# 重定位模型
relocation-model = "pic"

# 目标CPU
target-cpu = "generic"

# 目标特性
target-feature = ""

# 链接器
linker = ""

# 链接器参数
link-args = []

# 运行时库
crt-static = false

# 标准库
std = true

# 基准测试配置
[bench]
# 基准测试目标
target = "x86_64-pc-windows-msvc"

# 基准测试目录
target-dir = "target"

# 并行基准测试
jobs = 0

# 基准测试脚本
bench-script = ""

# 输出目录
out-dir = "target/release"

# 增量编译
incremental = false

# 调试信息
debug = false

# 优化级别
opt-level = 3

# 链接时优化
lto = "fat"

# 代码生成单元
codegen-units = 1

# Panic策略
panic = "abort"

# 符号剥离
strip = "symbols"

# 帧指针
force-frame-pointers = false

# 重定位模型
relocation-model = "static"

# 目标CPU
target-cpu = "native"

# 目标特性
target-feature = "+crt-static,+avx2,+fma,+bmi2,+popcnt,+sse4.2"

# 链接器
linker = ""

# 链接器参数
link-args = []

# 运行时库
crt-static = true

# 标准库
std = true
