# Rust 工具链配置文件 - 2025年10月16日最新设置
# 支持Rust 1.90新特性和性能优化

[toolchain]
# 使用最新的稳定版本 (Rust 1.90)
channel = "stable"
# 或者指定具体版本: channel = "1.90.0"

# 目标平台配置
targets = [
    "x86_64-pc-windows-msvc",    # Windows 64位
]

# 组件配置 - Rust 1.90 兼容
components = [
    "rustfmt",      # 代码格式化
    "clippy",       # 代码检查
    "rust-src",     # 标准库源码
    "rust-analyzer", # 语言服务器
    "rust-docs",    # 文档
    "cargo",        # 包管理器（包含 fmt 和 clippy 功能）
]

# 配置文件
profile = "default"

# 工具链覆盖
[toolchain.override]
# 可以在这里覆盖特定目录的工具链设置

# 注意：rust-toolchain.toml 主要用于指定工具链版本和组件
# 详细的构建配置应该在 .cargo/config.toml 或 Cargo.toml 中设置
