apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "otlp.fullname" . }}
spec:
  hosts:
    - "*"
  gateways:
    - mesh
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "otlp.fullname" . }}
            port:
              number: 80

