apiVersion: v2
name: otlp-server
description: A Helm chart for OTLP Rust Server
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/your-org/otlp-rust
sources:
  - https://github.com/your-org/otlp-rust
maintainers:
  - name: OTLP Team
    email: team@otlp-rust.com
keywords:
  - otlp
  - opentelemetry
  - rust
  - observability
  - telemetry
annotations:
  category: Observability
