# OTLP标准版本自动监控
# 
# 功能:
# 1. 每天检查OpenTelemetry标准仓库的最新版本
# 2. 对比本地记录的版本信息
# 3. 发现新版本时自动创建Issue提醒
# 4. 生成版本对比报告

name: OTLP Version Monitor

on:
  # 每天UTC 00:00执行 (北京时间08:00)
  schedule:
    - cron: '0 0 * * *'
  
  # 手动触发
  workflow_dispatch:
  
  # PR时检查
  pull_request:
    paths:
      - 'version-tracking/**'

env:
  # 监控的仓库
  OTLP_SPEC_REPO: 'open-telemetry/opentelemetry-proto'
  SEMCONV_REPO: 'open-telemetry/semantic-conventions'
  COLLECTOR_REPO: 'open-telemetry/opentelemetry-collector'

jobs:
  check-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        pip install requests pyyaml jinja2 packaging
    
    - name: Create Version Tracking Directory
      run: |
        mkdir -p version-tracking
        mkdir -p version-tracking/reports
    
    - name: Fetch Latest OTLP Spec Version
      id: otlp-spec
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/${{ env.OTLP_SPEC_REPO }}/releases/latest | jq -r .tag_name)
        RELEASE_DATE=$(curl -s https://api.github.com/repos/${{ env.OTLP_SPEC_REPO }}/releases/latest | jq -r .published_at)
        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "date=$RELEASE_DATE" >> $GITHUB_OUTPUT
        echo "✅ OTLP Spec: $LATEST_TAG ($RELEASE_DATE)"
    
    - name: Fetch Latest Semantic Conventions Version
      id: semconv
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/${{ env.SEMCONV_REPO }}/releases/latest | jq -r .tag_name)
        RELEASE_DATE=$(curl -s https://api.github.com/repos/${{ env.SEMCONV_REPO }}/releases/latest | jq -r .published_at)
        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "date=$RELEASE_DATE" >> $GITHUB_OUTPUT
        echo "✅ Semantic Conventions: $LATEST_TAG ($RELEASE_DATE)"
    
    - name: Fetch Latest Collector Version
      id: collector
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/${{ env.COLLECTOR_REPO }}/releases/latest | jq -r .tag_name)
        RELEASE_DATE=$(curl -s https://api.github.com/repos/${{ env.COLLECTOR_REPO }}/releases/latest | jq -r .published_at)
        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "date=$RELEASE_DATE" >> $GITHUB_OUTPUT
        echo "✅ Collector: $LATEST_TAG ($RELEASE_DATE)"
    
    - name: Load Current Versions
      id: current
      run: |
        if [ -f version-tracking/current-versions.yml ]; then
          cat version-tracking/current-versions.yml
        else
          echo "⚠️ No version tracking file found, will create new one"
        fi
    
    - name: Compare Versions and Generate Report
      id: compare
      run: |
        python3 << 'EOF'
        import os
        import yaml
        import json
        from datetime import datetime
        from pathlib import Path
        
        # 获取最新版本
        latest_versions = {
            'otlp_spec': {
                'version': '${{ steps.otlp-spec.outputs.version }}',
                'date': '${{ steps.otlp-spec.outputs.date }}',
                'repo': '${{ env.OTLP_SPEC_REPO }}'
            },
            'semantic_conventions': {
                'version': '${{ steps.semconv.outputs.version }}',
                'date': '${{ steps.semconv.outputs.date }}',
                'repo': '${{ env.SEMCONV_REPO }}'
            },
            'collector': {
                'version': '${{ steps.collector.outputs.version }}',
                'date': '${{ steps.collector.outputs.date }}',
                'repo': '${{ env.COLLECTOR_REPO }}'
            }
        }
        
        # 读取当前版本
        version_file = Path('version-tracking/current-versions.yml')
        if version_file.exists():
            with open(version_file, 'r') as f:
                current_versions = yaml.safe_load(f) or {}
        else:
            current_versions = {}
        
        # 对比版本
        updates = []
        for key, latest in latest_versions.items():
            current = current_versions.get(key, {})
            if current.get('version') != latest['version']:
                updates.append({
                    'name': key,
                    'old_version': current.get('version', 'N/A'),
                    'new_version': latest['version'],
                    'repo': latest['repo']
                })
                print(f"🆕 Update detected: {key} {current.get('version', 'N/A')} → {latest['version']}")
        
        # 输出结果
        if updates:
            with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                f.write(f"has_updates=true\n")
                f.write(f"update_count={len(updates)}\n")
            
            # 保存更新详情
            with open('version-tracking/updates.json', 'w') as f:
                json.dump(updates, f, indent=2)
        else:
            with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                f.write(f"has_updates=false\n")
            print("✅ All versions are up to date")
        
        # 更新版本文件
        current_versions.update(latest_versions)
        current_versions['last_checked'] = datetime.utcnow().isoformat()
        
        with open('version-tracking/current-versions.yml', 'w') as f:
            yaml.dump(current_versions, f, default_flow_style=False, sort_keys=False)
        
        EOF
    
    - name: Generate Update Report
      if: steps.compare.outputs.has_updates == 'true'
      run: |
        python3 << 'EOF'
        import json
        from datetime import datetime
        
        with open('version-tracking/updates.json', 'r') as f:
            updates = json.load(f)
        
        report = f"""# OTLP标准版本更新报告
        
        **检测时间**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}  
        **发现更新**: {len(updates)}个
        
        ---
        
        ## 📦 版本更新详情
        
        """
        
        for update in updates:
            name_display = {
                'otlp_spec': 'OTLP Protocol Specification',
                'semantic_conventions': 'Semantic Conventions',
                'collector': 'OpenTelemetry Collector'
            }
            
            report += f"""
        ### {name_display.get(update['name'], update['name'])}
        
        - **仓库**: `{update['repo']}`
        - **旧版本**: `{update['old_version']}`
        - **新版本**: `{update['new_version']}` 🆕
        - **变更链接**: https://github.com/{update['repo']}/compare/{update['old_version']}...{update['new_version']}
        - **Release Notes**: https://github.com/{update['repo']}/releases/tag/{update['new_version']}
        
        **需要更新的文档**:
        """
            
            if 'otlp_spec' in update['name']:
                report += """
        - [ ] `01_OTLP核心协议/01_协议概述.md`
        - [ ] `01_OTLP核心协议/02_gRPC传输.md`
        - [ ] `01_OTLP核心协议/03_HTTP传输.md`
        - [ ] `03_数据模型/` (Traces/Metrics/Logs)
        """
            elif 'semantic_conventions' in update['name']:
                report += """
        - [ ] `02_Semantic_Conventions/00_语义约定总览.md`
        - [ ] `02_Semantic_Conventions/01_通用协议属性/`
        - [ ] `02_Semantic_Conventions/02_追踪属性/`
        - [ ] `02_Semantic_Conventions/03_指标属性/`
        """
            elif 'collector' in update['name']:
                report += """
        - [ ] `04_核心组件/01_Collector架构.md`
        - [ ] `04_核心组件/02_接收器.md`
        - [ ] `04_核心组件/03_处理器.md`
        - [ ] `04_核心组件/04_导出器.md`
        """
            
            report += "\n---\n"
        
        report += f"""
        ## 🔄 下一步行动
        
        1. **审查变更**: 查看上述Release Notes,了解具体变更内容
        2. **评估影响**: 判断哪些现有文档需要更新
        3. **更新文档**: 根据新版本更新相应文档
        4. **测试验证**: 验证代码示例是否仍然有效
        5. **关闭Issue**: 完成更新后关闭本Issue
        
        ## 📋 更新检查清单
        
        - [ ] 已审查所有Release Notes
        - [ ] 已识别需要更新的文档
        - [ ] 已完成文档更新
        - [ ] 已验证代码示例
        - [ ] 已更新版本号标识
        - [ ] 已提交PR
        
        ---
        
        *本报告由GitHub Actions自动生成*  
        *Workflow: `.github/workflows/otlp-version-monitor.yml`*
        """
        
        with open('version-tracking/reports/update-report-latest.md', 'w') as f:
            f.write(report)
        
        # 保存Issue内容
        with open('version-tracking/issue-body.md', 'w') as f:
            f.write(report)
        
        print("✅ Report generated")
        print(report)
        EOF
    
    - name: Create Issue for Updates
      if: steps.compare.outputs.has_updates == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const issueBody = fs.readFileSync('version-tracking/issue-body.md', 'utf8');
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `🔔 OTLP标准版本更新检测 - ${new Date().toISOString().split('T')[0]}`,
            body: issueBody,
            labels: ['version-update', 'P0', 'documentation']
          });
    
    - name: Commit Updated Versions
      if: steps.compare.outputs.has_updates == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add version-tracking/
        git commit -m "chore: update OTLP version tracking [skip ci]" || echo "No changes to commit"
        git push || echo "Nothing to push"
    
    - name: Upload Report as Artifact
      if: steps.compare.outputs.has_updates == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: version-update-report-${{ github.run_number }}
        path: version-tracking/reports/
        retention-days: 90
    
    - name: Send Notification (Optional)
      if: steps.compare.outputs.has_updates == 'true'
      run: |
        echo "::notice::发现 ${{ steps.compare.outputs.update_count }} 个版本更新,已创建Issue"
    
    - name: Summary
      run: |
        echo "## 📊 版本检查摘要" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| 组件 | 版本 | 发布日期 |" >> $GITHUB_STEP_SUMMARY
        echo "|------|------|----------|" >> $GITHUB_STEP_SUMMARY
        echo "| OTLP Spec | ${{ steps.otlp-spec.outputs.version }} | ${{ steps.otlp-spec.outputs.date }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Semantic Conventions | ${{ steps.semconv.outputs.version }} | ${{ steps.semconv.outputs.date }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Collector | ${{ steps.collector.outputs.version }} | ${{ steps.collector.outputs.date }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.compare.outputs.has_updates }}" == "true" ]; then
          echo "🆕 **发现 ${{ steps.compare.outputs.update_count }} 个版本更新!**" >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ **所有版本都是最新的**" >> $GITHUB_STEP_SUMMARY
        fi

  # 可选: 每周生成完整的版本历史报告
  weekly-report:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * 0'  # 每周日
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Generate Weekly Report
      run: |
        python3 << 'EOF'
        import yaml
        from datetime import datetime, timedelta
        from pathlib import Path
        
        version_file = Path('version-tracking/current-versions.yml')
        if not version_file.exists():
            print("No version data available")
            exit(0)
        
        with open(version_file, 'r') as f:
            versions = yaml.safe_load(f)
        
        report = f"""# OTLP标准版本周报
        
        **报告周期**: {(datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')} ~ {datetime.now().strftime('%Y-%m-%d')}
        
        ## 📦 当前版本
        
        | 组件 | 版本 | 发布日期 | 仓库 |
        |------|------|----------|------|
        """
        
        for key, data in versions.items():
            if key == 'last_checked':
                continue
            name = key.replace('_', ' ').title()
            report += f"| {name} | {data['version']} | {data['date'][:10]} | [{data['repo']}](https://github.com/{data['repo']}) |\n"
        
        report += f"""
        
        ## 📈 版本趋势
        
        - 最近一周未发现重大版本更新
        - 文档保持与最新标准同步
        
        ## 🔗 有用链接
        
        - [OTLP Specification](https://github.com/open-telemetry/opentelemetry-proto)
        - [Semantic Conventions](https://github.com/open-telemetry/semantic-conventions)
        - [Collector Releases](https://github.com/open-telemetry/opentelemetry-collector/releases)
        
        ---
        
        *上次检查时间: {versions.get('last_checked', 'N/A')}*
        """
        
        Path('version-tracking/reports').mkdir(parents=True, exist_ok=True)
        with open(f'version-tracking/reports/weekly-{datetime.now().strftime("%Y%m%d")}.md', 'w') as f:
            f.write(report)
        
        print(report)
        EOF
    
    - name: Upload Weekly Report
      uses: actions/upload-artifact@v4
      with:
        name: weekly-report-${{ github.run_number }}
        path: version-tracking/reports/weekly-*.md
        retention-days: 365

