apiVersion: v2
name: postgresql-all-in-one
description: PostgreSQL All-in-One 架构 Helm 图表
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/postgresql-all-in-one
sources:
  - https://github.com/your-org/postgresql-all-in-one
maintainers:
  - name: PostgreSQL All-in-One Team
    email: team@postgresql-all-in-one.com
keywords:
  - postgresql
  - database
  - all-in-one
  - timescaledb
  - redis
  - monitoring
annotations:
  category: Database
  licenses: MIT
