apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vector.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
    component: data-pipeline
data:
  vector.toml: |
    data_dir = "{{ .Values.config.data_dir }}"
    
    [log]
    level = "{{ .Values.config.log.level }}"
    file = "{{ .Values.config.log.file }}"
    
    [api]
    enabled = {{ .Values.config.api.enabled }}
    address = "{{ .Values.config.api.address }}"
    playground = {{ .Values.config.api.playground }}
    
    # Data Sources
    {{- range $key, $value := .Values.config.sources }}
    [sources.{{ $key }}]
    {{- range $subkey, $subvalue := $value }}
    {{- if kindIs "map" $subvalue }}
    {{ $subkey }} = { {{- range $k, $v := $subvalue }}{{ $k }} = {{ $v | toJson }}{{ end }} }
    {{- else }}
    {{ $subkey }} = {{ $subvalue | toJson }}
    {{- end }}
    {{- end }}
    {{- end }}
    
    # Data Transforms
    {{- range $key, $value := .Values.config.transforms }}
    [transforms.{{ $key }}]
    {{- range $subkey, $subvalue := $value }}
    {{- if kindIs "map" $subvalue }}
    {{ $subkey }} = { {{- range $k, $v := $subvalue }}{{ $k }} = {{ $v | toJson }}{{ end }} }
    {{- else }}
    {{ $subkey }} = {{ $subvalue | toJson }}
    {{- end }}
    {{- end }}
    {{- end }}
    
    # Data Sinks
    {{- range $key, $value := .Values.config.sinks }}
    [sinks.{{ $key }}]
    {{- range $subkey, $subvalue := $value }}
    {{- if kindIs "map" $subvalue }}
    {{ $subkey }} = { {{- range $k, $v := $subvalue }}{{ $k }} = {{ $v | toJson }}{{ end }} }
    {{- else }}
    {{ $subkey }} = {{ $subvalue | toJson }}
    {{- end }}
    {{- end }}
    {{- end }}
