apiVersion: v1
kind: Service
metadata:
  name: {{ include "vector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vector.selectorLabels" . | nindent 4 }}

