apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
    component: data-pipeline
spec:
  serviceName: {{ include "vector.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vector.selectorLabels" . | nindent 8 }}
        component: data-pipeline
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: api
          containerPort: {{ .Values.service.ports.api }}
          protocol: TCP
        - name: metrics
          containerPort: {{ .Values.service.ports.metrics }}
          protocol: TCP
        - name: http
          containerPort: {{ .Values.service.ports.http }}
          protocol: TCP
        {{- range .Values.env }}
        env:
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: vector-config
          mountPath: /etc/vector
        - name: vector-data
          mountPath: /var/lib/vector
        {{- range .Values.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: vector-config
        configMap:
          name: {{ include "vector.fullname" . }}-config
      {{- range .Values.hostPathVolumes }}
      - name: {{ .name }}
        hostPath:
          path: {{ .path }}
          type: {{ .type }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: vector-data
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
  {{- end }}
