apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: otlp-server-hpa
  namespace: otlp-system
  labels:
    app: otlp-server
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: otlp-server
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: otlp_requests_per_second
      target:
        type: AverageValue
        averageValue: "1000"
  - type: Pods
    pods:
      metric:
        name: otlp_response_time_p95
      target:
        type: AverageValue
        averageValue: "100m"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: otlp-server
  namespace: otlp-system
  labels:
    app: otlp-server
    component: monitoring
spec:
  selector:
    matchLabels:
      app: otlp-server
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'otlp_.*'
      action: keep
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otlp-server-pdb
  namespace: otlp-system
  labels:
    app: otlp-server
    component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: otlp-server
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: otlp-server-netpol
  namespace: otlp-system
  labels:
    app: otlp-server
    component: security
spec:
  podSelector:
    matchLabels:
      app: otlp-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: istio-system
    - podSelector:
        matchLabels:
          app: otlp-client
    ports:
    - protocol: TCP
      port: 4317
    - protocol: TCP
      port: 4318
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 14268
    - protocol: TCP
      port: 9090
    - protocol: TCP
      port: 9093
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
