apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  labels:
    app: pyroscope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
        - name: pyroscope
          image: grafana/pyroscope:1.6.0
          ports:
            - containerPort: 4040
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  labels:
    app: pyroscope
spec:
  selector:
    app: pyroscope
  ports:
    - name: http
      port: 4040
      targetPort: 4040
