apiVersion: batch/v1
kind: Job
metadata:
  name: tracegen
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: tracegen
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/tracegen:latest
          args:
            - "--otlp-endpoint=otel-collector:4317"
            - "--otlp-insecure=true"
            - "--traces=100000"
            - "--rate=10"
